Initialising the numpy

In [2]:

import numpy as np
arr = np.array([1,2,3])
print(arr)


[1 2 3]


In [3]:
shape = arr.shape
print(shape)

(3,)


In [4]:
l1 = [1,2,3]
l2 = [4,5,6]
l3 = [7,8,9]
arr1 = np.array([l1,l2,l3])
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
arr1.shape

(3, 3)

In [6]:
print(arr1[0])

[1 2 3]


#Indexing in the 2d array

In [7]:
arr1[1:3,2:3]

array([[6],
       [9]])

In [8]:
print(arr < 2)

[ True False False]


In [9]:
arr[arr < 2]

array([1])

In [13]:
np.arange(1,20,2).reshape(2,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [14]:
np.ones((5,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.zeros((4,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.random.randint(10,50)


10

In [20]:
np.random.randn(5,6)

array([[ 0.02406035,  0.74357234,  0.83855013, -0.02316873, -1.02464549,
        -1.68348018],
       [-0.76074704, -0.73752141, -1.30555908, -1.84033209, -1.39408929,
         0.04059552],
       [ 1.26326518, -0.44467946,  1.25239898,  1.56287605,  0.29542528,
        -0.73752379],
       [ 0.71705434, -0.17365825,  0.94461299, -0.02183369,  1.86035587,
         1.91598894],
       [-0.39541757, -0.28145509, -0.36723423,  0.42017957,  1.17275041,
        -0.25722184]])

In [ ]:
np.random.