Initialising the numpy

In [ ]:

import numpy as np
arr = np.array([1,2,3])
print(arr)


In [ ]:
shape = arr.shape
print(shape)

(3,)


In [ ]:
l1 = [1,2,3]
l2 = [4,5,6]
l3 = [7,8,9]
arr1 = np.array([l1,l2,l3])
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr1.shape

(3, 3)

In [ ]:
print(arr1[0])

[1 2 3]


#Indexing in the 2d array

In [ ]:
arr1[1:3,2:3]

array([[6],
       [9]])

In [ ]:
print(arr < 2)

[ True False False]


In [ ]:
arr[arr < 2]

array([1])